### PR TITLE
fixing getPointerCoordinates call function

### PR DESCRIPTION
**Pull request by JuanjoOrt**

### CODE REVIEW

**Comment by yashash-pugalia** [comment]
++

**Review by diskomo — APPROVED** [review]
Have to use this patch on my latetst project. Working for me.

**Comment by leandrolid** [comment]
Working for me. Thanks.

**Comment by NiallRedMane** [comment]
Until this pr is merged, here is npm package that includes this fix
https://www.npmjs.com/package/@win11react/react-canvas-draw

**Pull request closed without merging**
